

#define AST_NODE_NAME_SPACE 0
#define AST_NODE_CODE_BLOCK 1
#define AST_NODE_STRUCT_DECLARATION 2
#define AST_NODE_VARIABLE_DECLARATION 3
#define AST_NODE_FUNCTION_DECLARATION 4


/* Ast Helper Definitions for get_node_type() */

#define AST_CLOSE_BRACE -1 // }


/* Name Space Type */

#define NAME_SPACE_TYPE_NAME_SPACE 0
#define NAME_SPACE_TYPE_CODE_BLOCK 1
#define NAME_SPACE_TYPE_STRUCT_BODY 2
